# Generated by Django 5.2.6 on 2026-03-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_pendingemailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingemailverification',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
