# Generated by Django 5.2.6 on 2026-04-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_surveyquestion_surveyattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='warga_lokal_region',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
