# Generated by Django 5.2.6 on 2026-04-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_user_warga_lokal_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='unggahan',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unggahan',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
